[project]
name = "day02-03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "이채영", email = "cy419036@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
day02-03 = "day02_03:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
